resolver: lts-18.16
packages:
- foo-bar-api
- foo-bar-api-gen
- foo-bar-api-server
- foo-bar-api-server-data
- foo-bar-api-server-data-gen
- foo-bar-api-server-gen
- foo-bar-cli
- foo-bar-client
- foo-bar-client-data
- foo-bar-data
- foo-bar-data-gen
extra-deps:
- autodocodec-0.0.0.0@sha256:d5cc71f7e09e8a74965b2f737a22418c058b23b18c43d7cecf810387a132a94a,1547
- autodocodec-schema-0.0.0.0@sha256:5fd444c2c7556448db41caccb4e6f7fdda13cb1a3263a9fde7920cf1f53b5905,1079
- autodocodec-yaml-0.0.0.0@sha256:8cf1aa3a016b38354edbe0f6842b11ca87cafb423aad4bfba5e6f35eb5247c46,1181


- github: NorfairKing/appendful
  commit: c0d9116d70b9aaf8374b6f10dd8d17998d498981
  subdirs:
  - appendful
  - appendful-persistent
  - genvalidity-appendful
- github: NorfairKing/mergeless
  commit: d6461cee62689c92b0dd2096efb94d280dad7d5a
  subdirs:
  - mergeless
  - mergeless-persistent
  - genvalidity-mergeless
- github: NorfairKing/mergeful
  commit: 48d5ba362342d10fdbc9a98148f1506848f13870
  subdirs:
  - mergeful
  - mergeful-persistent
  - genvalidity-mergeful
- github: NorfairKing/validity
  commit: 466bb2f140e62cae0d4fe3770681c3d74e99cf40
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector

nix:
  shell-file: shell.nix
