name:                foo-bar-api-server
version:             0.0.0.0
github:              "NorfairKing/foo-bar"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020-2022 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - appendful-persistent
    - bytestring
    - envparse
    - foo-bar-api
    - foo-bar-api-server-data
    - foo-bar-data
    - jose
    - mergeful
    - mergeful-persistent
    - mergeless
    - mergeless-persistent
    - monad-logger
    - mtl
    - optparse-applicative
    - password
    - password-instances
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - persistent-template
    - servant-auth-server
    - servant-server
    - text
    - time
    - wai
    - warp
    - yaml
    - yamlparse-applicative

executables:
  foo-bar-api-server:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      - foo-bar-api-server
